2024-07-31 16:47:29,461 - __main__ - ERROR - Couldn't create the spark session due to exception SparkSession.Builder.config() takes from 1 to 4 positional arguments but 5 were given
2024-07-31 16:47:29,461 - root - INFO - Streaming is being started...
2024-07-31 16:47:29,461 - root - WARNING - kafka dataframe could not be created because: cannot access free variable 'spark' where it is not associated with a value in enclosing scope
2024-07-31 16:47:29,461 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'spark_df' where it is not associated with a value
2024-07-31 16:47:50,301 - __main__ - ERROR - Couldn't create the spark session due to exception SparkSession.Builder.config() takes from 1 to 4 positional arguments but 5 were given
2024-07-31 16:47:50,302 - root - INFO - Streaming is being started...
2024-07-31 16:47:50,302 - root - WARNING - kafka dataframe could not be created because: cannot access free variable 'spark' where it is not associated with a value in enclosing scope
2024-07-31 16:47:50,302 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'spark_df' where it is not associated with a value
2024-07-31 16:52:07,477 - __main__ - ERROR - Couldn't create the spark session due to exception SparkSession.Builder.config() takes from 1 to 4 positional arguments but 5 were given
2024-07-31 16:52:07,477 - root - INFO - Streaming is being started...
2024-07-31 16:52:07,477 - root - WARNING - kafka dataframe could not be created because: cannot access free variable 'spark' where it is not associated with a value in enclosing scope
2024-07-31 16:52:07,477 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'spark_df' where it is not associated with a value
2024-07-31 16:55:37,182 - __main__ - ERROR - Couldn't create the spark session due to exception SparkSession.Builder.config() takes from 1 to 4 positional arguments but 5 were given
2024-07-31 16:55:37,182 - root - INFO - Streaming is being started...
2024-07-31 16:55:37,182 - root - WARNING - kafka dataframe could not be created because: cannot access free variable 'spark' where it is not associated with a value in enclosing scope
2024-07-31 16:55:37,182 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'spark_df' where it is not associated with a value
2024-07-31 17:01:55,004 - __main__ - INFO - Spark connection created successfully!
2024-07-31 17:01:55,005 - root - INFO - Streaming is being started...
2024-07-31 17:01:55,176 - root - WARNING - kafka dataframe could not be created because: The value of property spark.hadoop.fs.s3a.secret.key must not be null

JVM stacktrace:
java.lang.IllegalArgumentException: The value of property spark.hadoop.fs.s3a.secret.key must not be null
	at org.apache.hadoop.thirdparty.com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1403)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1384)
	at org.apache.spark.sql.internal.SharedState.$anonfun$x$1$2(SharedState.scala:77)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
	at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:69)
	at org.apache.spark.sql.SparkSession.$anonfun$sharedState$1(SparkSession.scala:143)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:143)
	at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:142)
	at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:162)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:160)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:157)
	at org.apache.spark.sql.streaming.DataStreamReader.<init>(DataStreamReader.scala:380)
	at org.apache.spark.sql.SparkSession.readStream(SparkSession.scala:794)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)

2024-07-31 17:01:55,177 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'spark_df' where it is not associated with a value
2024-07-31 17:01:55,182 - py4j.clientserver - INFO - Closing down clientserver connection
2024-07-31 17:06:39,717 - __main__ - INFO - Spark connection created successfully!
2024-07-31 17:06:39,718 - root - INFO - Streaming is being started...
2024-07-31 17:06:41,827 - root - WARNING - kafka dataframe could not be created because: An error occurred while calling o42.load.
: java.lang.NoClassDefFoundError: scala/$less$colon$less
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.org$apache$spark$sql$kafka010$KafkaSourceProvider$$validateStreamOptions(KafkaSourceProvider.scala:338)
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.sourceSchema(KafkaSourceProvider.scala:71)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:233)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:118)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:118)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:36)
	at org.apache.spark.sql.streaming.DataStreamReader.loadInternal(DataStreamReader.scala:169)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: scala.$less$colon$less
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 more

2024-07-31 17:06:41,827 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'spark_df' where it is not associated with a value
2024-07-31 17:06:41,832 - py4j.clientserver - INFO - Closing down clientserver connection
2024-07-31 17:15:40,694 - __main__ - INFO - Spark connection created successfully!
2024-07-31 17:15:40,695 - root - INFO - Streaming is being started...
2024-07-31 17:15:42,533 - root - WARNING - kafka dataframe could not be created because: An error occurred while calling o42.load.
: java.lang.NoClassDefFoundError: scala/$less$colon$less
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.org$apache$spark$sql$kafka010$KafkaSourceProvider$$validateStreamOptions(KafkaSourceProvider.scala:338)
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.sourceSchema(KafkaSourceProvider.scala:71)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:233)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:118)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:118)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:36)
	at org.apache.spark.sql.streaming.DataStreamReader.loadInternal(DataStreamReader.scala:169)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: scala.$less$colon$less
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 more

2024-07-31 17:15:42,534 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'spark_df' where it is not associated with a value
2024-07-31 17:15:42,541 - py4j.clientserver - INFO - Closing down clientserver connection
2024-07-31 18:57:07,997 - __main__ - INFO - Spark connection created successfully!
2024-07-31 18:57:07,998 - root - INFO - Streaming is being started...
2024-07-31 18:57:10,468 - root - WARNING - kafka dataframe could not be created because: An error occurred while calling o42.load.
: java.lang.NoClassDefFoundError: scala/$less$colon$less
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.org$apache$spark$sql$kafka010$KafkaSourceProvider$$validateStreamOptions(KafkaSourceProvider.scala:338)
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.sourceSchema(KafkaSourceProvider.scala:71)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:233)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:118)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:118)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:36)
	at org.apache.spark.sql.streaming.DataStreamReader.loadInternal(DataStreamReader.scala:169)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: scala.$less$colon$less
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 more

2024-07-31 18:57:10,469 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'spark_df' where it is not associated with a value
2024-07-31 18:57:10,473 - py4j.clientserver - INFO - Closing down clientserver connection
2024-07-31 19:11:20,891 - __main__ - INFO - Spark connection created successfully!
2024-07-31 19:11:20,893 - root - INFO - Streaming is being started...
2024-07-31 19:11:22,897 - root - WARNING - kafka dataframe could not be created because: An error occurred while calling o42.load.
: java.lang.NoClassDefFoundError: scala/$less$colon$less
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.org$apache$spark$sql$kafka010$KafkaSourceProvider$$validateStreamOptions(KafkaSourceProvider.scala:338)
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.sourceSchema(KafkaSourceProvider.scala:71)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:233)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:118)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:118)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:36)
	at org.apache.spark.sql.streaming.DataStreamReader.loadInternal(DataStreamReader.scala:169)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: scala.$less$colon$less
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 more

2024-07-31 19:11:22,899 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
UnboundLocalError: local variable 'spark_df' referenced before assignment
2024-07-31 19:11:22,901 - py4j.clientserver - INFO - Closing down clientserver connection
2024-07-31 19:28:27,378 - __main__ - INFO - Spark connection created successfully!
2024-07-31 19:28:27,380 - root - INFO - Streaming is being started...
2024-07-31 19:28:29,708 - root - WARNING - kafka dataframe could not be created because: An error occurred while calling o42.load.
: java.lang.NoClassDefFoundError: scala/$less$colon$less
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.org$apache$spark$sql$kafka010$KafkaSourceProvider$$validateStreamOptions(KafkaSourceProvider.scala:338)
	at org.apache.spark.sql.kafka010.KafkaSourceProvider.sourceSchema(KafkaSourceProvider.scala:71)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:233)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:118)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:118)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:36)
	at org.apache.spark.sql.streaming.DataStreamReader.loadInternal(DataStreamReader.scala:169)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: scala.$less$colon$less
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 more

2024-07-31 19:28:29,709 - __main__ - ERROR - Error in streaming application
Traceback (most recent call last):
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 90, in main
    tickerDf = read_kafka_topic('market_data_topic', schema).alias('market')
  File "/Users/naman/Desktop/Projects/Algo-IIFL/API_Consumer candle.py", line 72, in read_kafka_topic
    return spark_df
UnboundLocalError: local variable 'spark_df' referenced before assignment
2024-07-31 19:28:29,713 - py4j.clientserver - INFO - Closing down clientserver connection
